// =============================================================================
// SimulatorPlugin.cpp
// =============================================================================
#include "SimulatorPlugin.h"
// moc_IFieldBus.cpp — auto-generated by Qt MOC, not needed here
